name: React CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: |
<<<<<<< HEAD
        npm install
=======
        npm ci
>>>>>>> 25508ecf4df8c354434212a3636b9758fc2d187c
        npm install react-router-dom@7.3.0
      
    - name: Run linter
      run: npm run lint || true
      
    - name: Run tests
      run: npm test -- --passWithNoTests
      
    - name: Build
      run: npm run build